### PR TITLE
#164 added alignment config option for level item component

### LINKED ISSUE #164: Level Item component has text centered if it's directly in Level component
The Level Item component has always been text-centered if it's directly in the Level component.

**Steps to reproduce**
1. Go to Bulma page
2. Add Level component
3. Add Level item component to Level component
4. Add Container and Title or Content component

**Current result**
The text is centered and there is no option to change that

**Expected behavior**
Possibility to have text aligned to the left.

**Screenshots**
Screenshot 2023-04-18 at 10 50 36

### PR DESCRIPTION
**Pull request by Rafal-DS**
## Description

Added alignment config option for author.

## Motivation and Context

https://github.com/websight-io/bulma/issues/164

## Screenshots (if appropriate)
Screenshot 2023-04-26 at 11 53 25

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

### CODE REVIEW

File: application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java [hunk 1]
```diff
@@ -44,11 +44,24 @@ public class LevelItemComponent {
...
   @PostConstruct
   private void init() {
     if (LEVEL_COMPONENT_RESOURCE_TYPE.equals(resource.getParent().getResourceType())) {
       levelItemStyle = "has-text-centered";
     }
   }
+
+  public String getAlignment() {
+    if (alignment.equals("is-left")) {
+      return "is-justify-content-flex-start";
```
Comment (paweljozwicki) [inline application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java]: Would it work for a more complex structure? I mean we could put a container to the level item and some contents inside the container. I think we have to use has-text-left/center/right? And by default we should use has-text-left

Comment (AdrianStaskiewicz) [reply application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java]: I had same question in my head.. Rest changes look good

**Review by AdrianStaskiewicz — COMMENTED** [review]
Looks ok, just one open question to discuss

File: application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java (hunk 1 above)
Comment (paweljozwicki) [reply application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java]: Or maybe we need both classes?

Comment (Rafal-DS) [reply application/backend/src/main/java/pl/ds/bulma/components/models/level/LevelItemComponent.java]: I think we need both classes. I updated the code.

**Review by paweljozwicki — APPROVED** [review]
